services:
  frontend:
    build:
      context: ./frontend
    expose:
      - "80:80"
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    expose:
      - "3000"
    environment:
      NODE_ENV: production
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
